on: [pull_request, push]
jobs:
  # The main CI workflow; installs dependencies, runs eslint, prettier, and jest.
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
# TODO: Return it back later after urgent fix
#    - run: npm run lint
    - run: npm run build
    - run: npm run test
