on: workflow_dispatch
jobs:
  # The main CI workflow; installs dependencies, runs eslint, prettier, and jest.
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - name: Create npm configuration
        run: echo "//npm.pkg.github.com/:_authToken=${token}" >> ~/.npmrc
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish
